apiVersion: skaffold/v2beta27
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: yonjuro/go-skaffold
      context: ./go-skaffold
      docker:
        dockerfile: Dockerfile
